name: API Tests
on:
  push:
    branches: [ master ]

jobs:
  tests:
    name: App Tests
    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [14.x]

    steps:
      - name: Chekcout Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Unit Tests
        run: npm test